[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
argon2 = "0.6"
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.12", features = ["cookie"] }
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
gethostname = "1"
getrandom = "0.4"
http-body-util = "0.1"
ipnet = { version = "2", features = ["serde"] }
pbkdf2 = { version = "0.13", features = ["phc", "getrandom"] }
rpassword = "7"
rust-embed = { version = "8", features = ["interpolate-folder-path", "mime-guess", "deterministic-timestamps"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-native-roots", "postgres", "macros", "migrate", "uuid", "ipnet", "chrono"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.7", features = ["set-header"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unicode-normalization = "0.1"
uuid = { version = "1", features = ["serde"] }

[profile.dev.package."*"]
opt-level = 2
